### PR TITLE
Loginpage

### PR DESCRIPTION
**Pull request by ybadmus**

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under the review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Work guys :clap: :clap: . However, you still need to implement the requirements below in order for us to approve your project:

#### Page structure

##### Intuit logo

* [x] It shows the Intuit logo above the form.
* [x] The intuit logo is an embedded image that is horizontally centered.

##### Intuit products

* [x] The products row is under the Intuit logo and above the form.
* [x] It shows the Mint logo and text (logo on the left, text on the right).
* [x] It shows the Quickbooks logo and text (logo on the left, text on the right).
* [x] It shows the Turbotax logo and text (logo on the left, text on the right).

### General Notes:
* [x] The project has to have a descriptive README.md
* [x] Run you html file through the [validator](validator.w3.org) and fix the errors
* [x] Follow the [instruction](https://github.com/microverseinc/linters-config/tree/master/css) to add linter to your project.

### That's it guys :relieved: . When finished implementing the above, kindly resubmit another code review request :pray: . Keep up the good work

**Comment by konyan** [comment]
@stratospherique 
please review my code. I am done in implementation.

**Comment by ybadmus** [comment]
Hello Ahmed,

Kindly take a look at our pull request and advice us on the reason why the
test is still failing.

It says we should add ".stickler.yml" file, I have already added it a
couple of times but the test is still not passing.

Best Regards
Yusuf

**Comment by stratospherique** [comment]
> Hello Ahmed, Kindly take a look at our pull request and advice us on the reason why the test is still failing. It says we should add ".stickler.yml" file, I have already added it a couple of times but the test is still not passing. Best Regards Yusuf


#### Hello team :eagle: . The stickler configuration is not set correctly. I would recommend following the instructions [here](https://github.com/microverseinc/linters-config/tree/master/css). :cat2: :cat2:

**Comment by konyan** [comment]
Hello @stratospherique , 
i don't still doesn't get about Stickler CI . its still failed. I already added about .yml file and config.js file in my branch loginpage.

**Comment by stratospherique** [comment]
The stickler works on your repository and it shows errors that you can fix easily. I think those errors don't appear in your code editor which mean you have to add a configuration using the **npm package manager** do the following:
- run `npm install stylelint stylelint-config-recommended --save-dev` (not sure how to use npm? Read this)
- copy `stylelint.config.js` to the root directory of your project
- run `npx stylelint` .
- The errors should appear in your local dev
:smile: :smile:

**Comment by konyan** [comment]
@stratospherique  thanks chief.

**Comment by konyan** [comment]
@stratospherique 
DONE

**Comment by offorma** [comment]
Well done guys, Nice job fixing the previous issues raised. I only noticed your input type for the phone field is of type text. You should use a type of tel. If you could change that then you have my thumbs up. There will be no need for another review. Happy learning with your next project.

**Pull request merged**
